# Collect Citcom CU Data
Basal Heating Only

In [10]:
%reset -f
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os 
import glob
from IPython.display import set_matplotlib_formats
from scipy.optimize import curve_fit
import re
import matplotlib.ticker as mticker
import math

%config InlineBackend.figure_formats = ['svg']

## Only 256 x 256 x 256

In [15]:
main_path = 'C:\\Users\\super\\Dropbox\\Rice University\\501\\BL_Interactions\\'
save_path = 'C:\\Users\\super\\Dropbox\\Rice University\\501\\BL_Interactions_Data\\'
# ra_path = ['1e4','1e5','1e6','1e7','1e8','1e9','1e10']

fname = os.path.join(main_path,'[!m]*')
fileL = glob.glob(fname) #list of files
fileL = [file.replace(main_path,'') for file in fileL]
[fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'Plume' in file];
ra_path = sorted (fileL, key = lambda x: (len (x), x))

newColOrder = ['Ra','NuT','NuB','VRMS','Surface']; Data = pd.DataFrame();

for i in range(len(ra_path)):
    dataRes = []
    fname = os.path.join(main_path+ra_path[i],'[!m]*')
    fileL = glob.glob(fname) #list of files
    fileL = [file.replace(main_path+ra_path[i]+'\\','') for file in fileL]
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'txt' in file];
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'txt' in file];
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'Plume' in file];
    [fileL.remove(file) for file in fileL if 'Plume' in file]; [fileL.remove(file) for file in fileL if 'Plume' in file];
    fileL = list(map(int, fileL)); fileL = sorted(fileL)
    dataRes = pd.DataFrame(fileL) #This gets the resolutions from folder names
    
    fname = os.path.join(main_path+ra_path[i],'[!m]*.txt')
    fileL = glob.glob(fname) #list of files
    temp = []
    for file in fileL:
        a = fileL.index(file)
        b = pd.read_csv(file,header=None)
        b.rename(columns={0:a}, inplace=True)
        b = b.tail(1)
        b = b.reset_index(drop=True)
        temp.append(b)
    c = b.copy()
    c.values[:] = ra_path[i]
    temp.append(c)

    my_data = pd.concat(temp, axis=1, join="inner",ignore_index=True)
    my_data.rename(columns={0:'NuT',1:'NuB',4:'Ra',3:'VRMS',2:'Surface'},inplace=True)
    my_data = my_data[newColOrder]
    Data = pd.concat([Data,my_data],ignore_index=True)

Data = Data.reset_index(drop=True)
Data = Data.sort_values(by=['Ra'])
Data.to_csv(save_path+'data_short.csv', index=False)
Data

              Ra         NuT         NuB           VRMS        Surface
0   1.000000e+04    4.656117    4.656052      32.962044      30.585930
1   1.000000e+05   11.254625   11.254650     168.172663     165.990000
2   1.000000e+06   23.502985   23.502726     704.028090     710.861606
6   3.000000e+06   31.091243   31.102263    1724.080856    1861.224138
3   1.000000e+07   45.752733   45.729992    3694.501261    3969.992941
7   3.000000e+07   61.203954   62.031461    6274.510580    6731.407576
4   1.000000e+08   85.241843   85.097414   13433.219966   13974.338182
8   3.000000e+08  128.210292  128.165251   28979.412563   30769.912037
10  6.000000e+08  163.818558  164.114764   47506.283676   50508.465035
5   1.000000e+09  173.733978  174.123207   43355.162240   40996.437276
9   3.000000e+09  239.050553  238.955733   81165.164700   75222.823219
11  6.000000e+09  291.512298  291.260261  122976.842941  114820.136029
12  1.000000e+10  348.805713  349.158726  166582.312656  156235.364621
13  3.000000e+10  480.417305  480.348149  321875.187770  292718.714286
14  6.000000e+10  623.178519  621.123524  496890.706307  469094.278075

## All Resolutions

In [16]:
main_path = 'C:\\Users\\super\\Dropbox\\Rice University\\501\\BL_Interactions\\'

# ra_path = ['1e4','1e5','1e6','1e7','1e8','1e9','1e10']

fname = os.path.join(main_path,'[!m]*')
fileL = glob.glob(fname) #list of files
fileL = [file.replace(main_path,'') for file in fileL]
[fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'Plume' in file];
ra_path = sorted (fileL, key = lambda x: (len (x), x))

newColOrder = ['Ra','Res','NuT','NuB','VRMS']; Data = pd.DataFrame();

for i in range(len(ra_path)):
    dataRes = []
    fname = os.path.join(main_path+ra_path[i],'[!m]*')
    fileL = glob.glob(fname) #list of files
    fileL = [file.replace(main_path+ra_path[i]+'\\','') for file in fileL]
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'txt' in file];
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'txt' in file];
    [fileL.remove(file) for file in fileL if '_' in file]; [fileL.remove(file) for file in fileL if 'Plume' in file];
    [fileL.remove(file) for file in fileL if 'Plume' in file];
    [fileL.remove(file) for file in fileL if 'Plume' in file];
    fileL = list(map(int, fileL)); fileL = sorted(fileL)
    dataRes = pd.DataFrame(fileL) #This gets the resolutions from folder names
    
    fname = os.path.join(main_path+ra_path[i],'[!m]*.txt')
    fileL = glob.glob(fname) #list of files
    [fileL.remove(file) for file in fileL if 'surface' in file];
    temp = []
    for file in fileL:
        a = fileL.index(file)
        b = pd.read_csv(file,header=None)
        b.rename(columns={0:a}, inplace=True)
        temp.append(b)
    c = b.copy()
    c.values[:] = ra_path[i]
    temp.append(c)

    my_data = pd.concat(temp, axis=1, join="inner",ignore_index=True)
    my_data.insert(3, 4, dataRes)
    my_data.rename(columns={0:'NuT',1:'NuB',3:'Ra',2:'VRMS',4:'Res'},inplace=True)
    my_data = my_data[newColOrder]
    Data = pd.concat([Data,my_data],ignore_index=True)


Data = Data.sort_values(by=['Ra'])
Data = Data.reset_index(drop=True)
Data.to_csv(save_path+'data_full.csv', index=False)
Data

              Ra  Res         NuT         NuB           VRMS
0   1.000000e+04   32    4.729123    4.729157      34.345420
1   1.000000e+04   64    4.703615    4.703550      33.989760
2   1.000000e+04  128    4.718800    4.718760      34.073796
3   1.000000e+04  256    4.656117    4.656052      32.962044
4   1.000000e+05   32   11.196491   11.196260     167.903258
5   1.000000e+05   64   11.218589   11.218611     167.546582
6   1.000000e+05  128   11.204573   11.204556     166.654630
7   1.000000e+05  256   11.254625   11.254650     168.172663
8   1.000000e+06  128   23.537548   23.537910     706.757331
9   1.000000e+06  256   23.502985   23.502726     704.028090
10  1.000000e+06   32   23.114366   23.113588     706.714569
11  1.000000e+06   64   23.298497   23.299051     701.748618
12  3.000000e+06   64   32.688286   32.705995    1375.575125
13  3.000000e+06  128   31.091243   30.144637    1507.031043
14  3.000000e+06   32   31.816469   31.814395    1388.655091
15  1.000000e+07   32   41.016478   40.162542    3086.118732
16  1.000000e+07   64   44.021680   43.784759    3158.954325
17  1.000000e+07  128   47.080276   47.072425    2848.147647
18  1.000000e+07  256   45.752733   45.729992    3694.501261
19  3.000000e+07  256   61.203954   62.031461    6274.510580
20  3.000000e+07  128   61.457021   61.378941    5953.483718
21  3.000000e+07   64   64.174421   64.234965    5622.735681
22  3.000000e+07   32   51.496686   52.068545    4965.709918
23  1.000000e+08   32   76.541480   75.084631    6405.966875
24  1.000000e+08  256   85.241843   85.097414   13433.219966
25  1.000000e+08  128   91.479502   91.432651   14360.654921
26  1.000000e+08   64   81.140731   81.342710    9144.472804
27  3.000000e+08  512  128.210292  128.165251   28979.412563
28  3.000000e+08   64   98.519382  105.407874   14494.872619
29  3.000000e+08  128  132.523250  132.006464   22855.362315
30  3.000000e+08  256  130.988048  131.153087   29119.044641
31  6.000000e+08  512  163.818558  164.114764   47506.283676
32  6.000000e+08  256  149.581901  149.238364   32284.956668
33  6.000000e+08  128  142.992865  143.312272   28252.117165
34  1.000000e+09  256  173.733978  174.123207   43355.162240
35  1.000000e+09  128  167.638382  168.277821   38617.716445
36  3.000000e+09  128  237.798169  237.995219   72936.777764
37  3.000000e+09  256  239.050553  238.955733   81165.164700
38  6.000000e+09  128  276.202212  266.634424   95035.893596
39  6.000000e+09  256  291.512298  291.260261  122976.842941
40  1.000000e+10  256  348.805713  349.158726  166582.312656
41  3.000000e+10  256  480.417305  480.348149  321875.187770
42  6.000000e+10  256  623.178519  621.123524  496890.706307